[package]
name = "request-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12.9", features = ["blocking", "json"]}
serde = { version = "1.0.214", features = ["derive"]}
tokio = "1.41.1"
